name: Build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: ''

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    continue-on-error: true

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
        cache: false

    - name: Display Go version
      run: |
        go version

    - name: Set ref and repo from PR or dispatch
      id: set-ref
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "pull_request_target" ]]; then
          echo "ref=${{ github.event.pull_request.head.ref }}" >> "$GITHUB_OUTPUT"
          echo "repo=${{ github.event.pull_request.head.repo.full_name }}" >> "$GITHUB_OUTPUT"
        else
          echo "ref=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          echo "repo=${{ github.repository }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Build urunc binaries
      id: build-urunc-binaries
      run: |
        make

    - name: Upload urunc_${{ matrix.arch }}
      uses: actions/upload-artifact@v4
      with:
        name: urunc_${{ matrix.arch }}-${{ github.run_id }}
        path: dist/urunc_static_${{ matrix.arch }}
    
    - name: Upload containerd-shim-urunc-v2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: containerd-shim-urunc-v2_${{ matrix.arch }}-${{ github.run_id }}
        path: dist/containerd-shim-urunc-v2_static_${{ matrix.arch }}
